### PR TITLE
Fixed GFortran Compilation Error

### LINKED ISSUE #11: [BUG] OpenFSAM Fails to Compile with GFortran 13.1.1
I'm not really sure what changed...

But now when I try to compile OpenFSAM, I get a compilation error from the GNU Fortran compiler [GNU Fortran (GCC) 13.1.1 20230429].

```
OpenFSAM.f90:162:11:

  162 |       TYPEIS(sa_comb_type)
      |           1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:163:50:

  163 |         thisSA%size_states=SIZE(thisSA%state_curr)
      |                                                  1
Error: ‘state_curr’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:164:46:

  164 |         IF(.NOT. ALLOCATED(thisSA%state_neigh))THEN
      |                                              1
Error: ‘state_neigh’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:165:38:

  165 |           ALLOCATE(thisSA%state_neigh(thisSA%size_states))
      |                                      1
Error: ‘state_neigh’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:166:11:

  166 |         ENDIF
      |           1
Error: Expecting END SELECT statement at (1)
OpenFSAM.f90:167:45:

  167 |         IF(.NOT. ALLOCATED(thisSA%state_best))THEN
      |                                             1
Error: ‘state_best’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘e_best’?
OpenFSAM.f90:168:37:

  168 |           ALLOCATE(thisSA%state_best(thisSA%size_states))
      |                                     1
Error: ‘state_best’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘e_best’?
OpenFSAM.f90:169:11:

  169 |         ENDIF
      |           1
Error: Expecting END SELECT statement at (1)
OpenFSAM.f90:170:27:

  170 |         thisSA%state_neigh=thisSA%state_curr
      |                           1
Error: ‘state_neigh’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:171:26:

  171 |         thisSA%state_best=thisSA%state_curr
      |                          1
Error: ‘state_best’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘e_best’?
OpenFSAM.f90:173:29:

  173 |         e_curr=thisSA%energy(thisSA%state_curr)
      |                             1
Error: ‘energy’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:174:28:

  174 |         thisSA%e_best=e_curr
      |                            1
Error: Expected TYPE IS, CLASS IS or END SELECT statement following SELECT TYPE at (1)
OpenFSAM.f90:175:11:

  175 |       TYPEIS(sa_cont_type)
      |           1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:176:50:

  176 |         thisSA%size_states=SIZE(thisSA%state_curr)
      |                                                  1
Error: ‘state_curr’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:177:46:

  177 |         IF(.NOT. ALLOCATED(thisSA%state_neigh))THEN
      |                                              1
Error: ‘state_neigh’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:178:38:

  178 |           ALLOCATE(thisSA%state_neigh(thisSA%size_states))
      |                                      1
Error: ‘state_neigh’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:179:11:

  179 |         ENDIF
      |           1
Error: Expecting END SELECT statement at (1)
OpenFSAM.f90:180:45:

  180 |         IF(.NOT. ALLOCATED(thisSA%state_best))THEN
      |                                             1
Error: ‘state_best’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘e_best’?
OpenFSAM.f90:181:37:

  181 |           ALLOCATE(thisSA%state_best(thisSA%size_states))
      |                                     1
Error: ‘state_best’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘e_best’?
OpenFSAM.f90:182:11:

  182 |         ENDIF
      |           1
Error: Expecting END SELECT statement at (1)
OpenFSAM.f90:183:27:

  183 |         thisSA%state_neigh=thisSA%state_curr
      |                           1
Error: ‘state_neigh’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:184:26:

  184 |         thisSA%state_best=thisSA%state_curr
      |                          1
Error: ‘state_best’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘e_best’?
OpenFSAM.f90:186:29:

  186 |         e_curr=thisSA%energy(thisSA%state_curr)
      |                             1
Error: ‘energy’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:187:28:

  187 |         thisSA%e_best=e_curr
      |                            1
Error: Expected TYPE IS, CLASS IS or END SELECT statement following SELECT TYPE at (1)
OpenFSAM.f90:189:23:

  189 |         IF(thisSA%smax-thisSA%smin .LT. 1.0D-13)THEN
      |                       1
Error: ‘smax’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘t_max’?
OpenFSAM.f90:190:22:

  190 |           thisSA%smax=MAXVAL(thisSA%state_curr)
      |                      1
Error: ‘smax’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘t_max’?
OpenFSAM.f90:191:22:

  191 |           thisSA%smin=MINVAL(thisSA%state_curr)
      |                      1
Error: ‘smin’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘t_min’?
OpenFSAM.f90:192:11:

  192 |         ENDIF
      |           1
Error: Expecting END SELECT statement at (1)
OpenFSAM.f90:193:26:

  193 |         IF(thisSA%damping .LE. 1.0D-15)thisSA%damping=ABS(thisSA%smax-thisSA%smin)/2.0D0
      |                          1
Error: ‘damping’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:194:11:

  194 |       TYPEIS(sa_disc_type)
      |           1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:195:50:

  195 |         thisSA%size_states=SIZE(thisSA%state_curr)
      |                                                  1
Error: ‘state_curr’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:196:46:

  196 |         IF(.NOT. ALLOCATED(thisSA%state_neigh))THEN
      |                                              1
Error: ‘state_neigh’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:197:38:

  197 |           ALLOCATE(thisSA%state_neigh(thisSA%size_states))
      |                                      1
Error: ‘state_neigh’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:198:11:

  198 |         ENDIF
      |           1
Error: Expecting END SELECT statement at (1)
OpenFSAM.f90:199:45:

  199 |         IF(.NOT. ALLOCATED(thisSA%state_best))THEN
      |                                             1
Error: ‘state_best’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘e_best’?
OpenFSAM.f90:200:37:

  200 |           ALLOCATE(thisSA%state_best(thisSA%size_states))
      |                                     1
Error: ‘state_best’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘e_best’?
OpenFSAM.f90:201:11:

  201 |         ENDIF
      |           1
Error: Expecting END SELECT statement at (1)
OpenFSAM.f90:204:45:

  204 |         IF(.NOT. ALLOCATED(thisSA%var_values))THEN
      |                                             1
Error: ‘var_values’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:205:38:

  205 |           CALL init_var_values(thisSA)
      |                                      1
Error: Expected TYPE IS, CLASS IS or END SELECT statement following SELECT TYPE at (1)
OpenFSAM.f90:206:11:

  206 |         ENDIF
      |           1
Error: Expecting END SELECT statement at (1)
OpenFSAM.f90:207:27:

  207 |         thisSA%state_neigh=thisSA%state_curr
      |                           1
Error: ‘state_neigh’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:208:26:

  208 |         thisSA%state_best=thisSA%state_curr
      |                          1
Error: ‘state_best’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘e_best’?
OpenFSAM.f90:210:29:

  210 |         e_curr=thisSA%energy(thisSA%state_curr)
      |                             1
Error: ‘energy’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:211:28:

  211 |         thisSA%e_best=e_curr
      |                            1
Error: Expected TYPE IS, CLASS IS or END SELECT statement following SELECT TYPE at (1)
OpenFSAM.f90:224:13:

  224 |         TYPEIS(sa_comb_type)
      |             1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:225:29:

  225 |           thisSA%state_neigh=thisSA%get_neigh(thisSA%state_curr)
      |                             1
Error: ‘state_neigh’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:226:32:

  226 |           e_neigh=thisSA%energy(thisSA%state_neigh)
      |                                1
Error: ‘energy’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:227:13:

  227 |         TYPEIS(sa_cont_type)
      |             1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:228:29:

  228 |           thisSA%state_neigh=thisSA%get_neigh(thisSA%state_curr,thisSA%damping,thisSA%smax,thisSA%smin)
      |                             1
Error: ‘state_neigh’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:229:32:

  229 |           e_neigh=thisSA%energy(thisSA%state_neigh)
      |                                1
Error: ‘energy’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:230:13:

  230 |         TYPEIS(sa_disc_type)
      |             1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:231:29:

  231 |           thisSA%state_neigh=thisSA%get_neigh(thisSA%state_curr)
      |                             1
Error: ‘state_neigh’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:232:32:

  232 |           e_neigh=thisSA%energy(thisSA%state_neigh)
      |                                1
Error: ‘energy’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:242:15:

  242 |           TYPEIS(sa_comb_type)
      |               1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:243:30:

  243 |             thisSA%state_curr=thisSA%state_neigh
      |                              1
Error: ‘state_curr’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:244:15:

  244 |           TYPEIS(sa_cont_type)
      |               1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:245:30:

  245 |             thisSA%state_curr=thisSA%state_neigh
      |                              1
Error: ‘state_curr’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:246:15:

  246 |           TYPEIS(sa_disc_type)
      |               1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:247:30:

  247 |             thisSA%state_curr=thisSA%state_neigh
      |                              1
Error: ‘state_curr’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:266:15:

  266 |           TYPEIS(sa_comb_type)
      |               1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:267:30:

  267 |             thisSA%state_best=thisSA%state_neigh
      |                              1
Error: ‘state_best’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘e_best’?
OpenFSAM.f90:268:15:

  268 |           TYPEIS(sa_cont_type)
      |               1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:269:30:

  269 |             thisSA%state_best=thisSA%state_neigh
      |                              1
Error: ‘state_best’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘e_best’?
OpenFSAM.f90:270:15:

  270 |           TYPEIS(sa_disc_type)
      |               1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:271:30:

  271 |             thisSA%state_best=thisSA%state_neigh
      |                              1
Error: ‘state_best’ at (1) is not a member of the ‘sa_type_base’ structure; did you mean ‘e_best’?
OpenFSAM.f90:279:15:

  279 |           TYPEIS(sa_comb_type)
      |               1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:280:32:

  280 |             e_curr=thisSA%e_best
      |                                1
Error: Expected TYPE IS, CLASS IS or END SELECT statement following SELECT TYPE at (1)
OpenFSAM.f90:281:30:

  281 |             thisSA%state_curr=thisSA%state_best
      |                              1
Error: ‘state_curr’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:282:15:

  282 |           TYPEIS(sa_cont_type)
      |               1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:283:32:

  283 |             e_curr=thisSA%e_best
      |                                1
Error: Expected TYPE IS, CLASS IS or END SELECT statement following SELECT TYPE at (1)
OpenFSAM.f90:284:30:

  284 |             thisSA%state_curr=thisSA%state_best
      |                              1
Error: ‘state_curr’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:285:31:

  285 |             IF(thisSA%damp_dyn)thisSA%damping=thisSA%damping/2.0D0
      |                               1
Error: ‘damp_dyn’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:286:15:

  286 |           TYPEIS(sa_disc_type)
      |               1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:287:32:

  287 |             e_curr=thisSA%e_best
      |                                1
Error: Expected TYPE IS, CLASS IS or END SELECT statement following SELECT TYPE at (1)
OpenFSAM.f90:288:30:

  288 |             thisSA%state_curr=thisSA%state_best
      |                              1
Error: ‘state_curr’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:297:11:

  297 |       TYPEIS(sa_comb_type)
      |           1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:298:26:

  298 |         thisSA%state_curr=thisSA%state_best
      |                          1
Error: ‘state_curr’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:299:11:

  299 |       TYPEIS(sa_cont_type)
      |           1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:300:26:

  300 |         thisSA%state_curr=thisSA%state_best
      |                          1
Error: ‘state_curr’ at (1) is not a member of the ‘sa_type_base’ structure
OpenFSAM.f90:301:11:

  301 |       TYPEIS(sa_disc_type)
      |           1
Error: Mangled derived type definition at (1)
OpenFSAM.f90:302:26:

  302 |         thisSA%state_curr=thisSA%state_best
      |                          1
Error: ‘state_curr’ at (1) is not a member of the ‘sa_type_base’ structure

```

### PR DESCRIPTION
**Pull request by NolantheNerd**
Resolves #11.

Apparently "TYPEIS" (without a space) is no longer acceptable to the GNU Fortran compiler (version 13.1.1). Separating the keyword into two words "TYPE IS" solves the compilation issue.

### CODE REVIEW

**Comment by nfherrin** [comment]
Looks good. I'm still on 11.3.0 so I haven't seen this pop up yet, but it doesn't break backwards compatibility to change it.
